<?php

use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Url;

/**
 * Implements hook_theme_suggestions_alter().
 */
function custom_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
    if($hook == 'menu'){
        $menus = ['main-lv', 'main-ru'];
        $footer_menus = ['footer-lv', 'footer-ru'];
        if(in_array($variables['menu_name'], $menus)){
            $suggestions[] = $hook . '__heder_menu';
        }
        if(in_array($variables['menu_name'], $footer_menus)){
            $suggestions[] = $hook . '__footer_menu';
        }
    }
    if($hook == 'status_messages'){
        $variables['attributes']['class'][] = 'message-box';
    }
    if($hook == 'views_view_unformatted'){
        $suggestions[] = $hook . '__gallery_grid';
    }
}

/**
 * Implements hook_preprocess_block().
 */
function custom_preprocess_block(&$variables) {
    $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $galleries = [];

    if($variables['plugin_id'] == 'views_block:first_page_header-block_1'){
        $config = \Drupal::config('system.site');
        $variables['site_name'] = $config->get('name');
        $variables['site_slogan'] = $config->get('slogan');
        $variables['block_data'] = getBlockSettingsFromConfig($variables)['hero_block'];
    }
    if($variables['plugin_id'] == 'views_block:about_block-block_1'){
        foreach ($variables['content']['#view']->result as $row) {
            $node = $row->_entity;
            if ($node->hasTranslation($language)){
                $node = $node->getTranslation($language);
            }
            $media = $node->field_attels->entity;
            if(isset($media)){
                $image = getMediaImage($media, 'wide');
            }else{
                $image = 'default';
            }
            $variables['title'] = getBlockSettingsFromConfig($variables)['about_block']['about_title'] ?? $node->label();
            $variables['body'] = $node->field_front_page_about_body->value ?? '';
            $variables['image'] = $image;
            $variables['url'] = $node->toUrl()->toString();
        }
    }
    if($variables['plugin_id'] == 'views_block:galleries-block_1'){
        foreach ($variables['content']['#view']->result as $row) {
            $node = $row->_entity;
            if ($node->hasTranslation($language)){
                $node = $node->getTranslation($language);
            }
            $highlight_image = $node->field_highlight->entity;
            if(isset($highlight_image)){
                $highlight = getMediaImage($highlight_image, 'fullhd');
            } else {
                $highlight = getMediaImage($node->field_bildes->entity, 'fullhd');
            }
            $galleries[] = [
                'title' => $node->label() ?? '',
                'image' => $highlight,
                'url' => $node->toUrl()->toString()
            ];
        }
        $variables['galleries_url'] = Url::fromRoute('view.galleries.page_1')->toString();
        $variables['block_data'] = getBlockSettingsFromConfig($variables)['gallery_block'];
    }
    $variables['galleries'] = $galleries;

}

/**
 * Get image style url from passed media and style
 * 
 * @param object $media
 * @param string $image_style
 * @return string
 */
function getMediaImage($media, $image_style){
    $file = $media->field_media_image->entity;
    if($file->getMimeType() == 'image/gif'){
        return $file->createFileUrl(false);
    }
    $uri = $file->getFileUri();
    return ImageStyle::load($image_style)->buildUrl($uri);
}

/**
 * Implements template_peprocess_node()
 */
function custom_preprocess_node(&$variables){
    $node = $variables['node'];
    if ($node->getType() == 'par_mums') {
        $media = $node->field_open_page_image->entity;
        if(isset($media)){
            $image = getMediaImage($media, 'fullhd');
        }else{
            $image = 'default';
        }
        $variables['title'] = $node->label() ?? '';
        $variables['body'] = $node->body->value ?? '';
        $variables['image'] = $image;
        $variables['url'] = $node->toUrl()->toString();
    } else if ($node->getType() == 'galerija' && $variables['view_mode'] == 'full') {
        foreach ($node->field_bildes->getIterator() as $value) {
            $media = $value->entity;
            if(isset($media)){
                $images[] = getMediaImage($media, 'fullhd');
            }
        }
        $highlight_image = $node->field_highlight->entity;
        if(isset($highlight_image)){
            $variables['highlight_image'] = getMediaImage($highlight_image, 'fullhd');
        }
        $variables['title'] = $node->label() ?? '';
        $variables['body'] = $node->body->value ?? '';
        $variables['images'] = $images;
    } else if ($node->getType() == 'galerija' && $variables['view_mode'] == 'teaser') {
        $highlight_image = $node->field_highlight->entity;
        if(isset($highlight_image)){
            $variables['highlight_image'] = getMediaImage($highlight_image, 'fullhd');
        } else {
            $variables['highlight_image'] = getMediaImage($node->field_bildes->entity, 'fullhd');
        }
        $variables['title'] = $node->label() ?? '';
        $variables['url'] = $node->toUrl()->toString();
    }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter()
 */
function custom_theme_suggestions_page_alter(array &$suggestions, array $variables){
    if ($node = \Drupal::routeMatch()->getParameter('node')){
        $suggestions[] = 'page__node__'. $node->bundle();
    }
}

/**
 * Implements template_preprocess_field()
 */
function custom_preprocess_field(&$variables){
    if (in_array($variables['field_type'], ['text_with_summary', 'text_long', 'string_long'])){
        $variables['attributes']['class'][] = 'cke_editable';
    }
}

/**
 * Implements custom_preprocess_webform
 */
function custom_preprocess_webform(&$variables){
    $wfid = $variables["element"]["#webform_id"];
    $wf = \Drupal\webform\Entity\Webform::load($wfid);
    $variables["title"] = getBlockSettingsFromConfig($variables)['contact_block']['contact_title'] ?? $wf->label();
    $variables['description'] = getBlockSettingsFromConfig($variables)['contact_block']['contact_description'] ?? null;
}

/**
 * Implements hook_preprocess_page
 */
function custom_preprocess_page(&$variables){
    $variables['footer_data'] = getBlockSettingsFromConfig($variables)['footer'];
}

/**
 * Get block titles and descriptions from config and insert in $variables array
 *
 * @param array $variables
 * @return array
 */
function getBlockSettingsFromConfig($variables) {
    $config = \Drupal::config('custom.block_settings');
    $variables['hero_block'] = [
        'hero_title' => $config->get('hero_title'),
        'hero_description' => $config->get('hero_description')
    ];
    $variables['about_block'] = [
        'about_title' => $config->get('about_title'),
    ];
    $variables['gallery_block'] = [
        'gallery_title' => $config->get('gallery_title'),
        'gallery_description' => $config->get('gallery_description'),
        'gallery_button_title' => $config->get('gallery_button_title')
    ];
    $variables['contact_block'] = [
        'contact_title' => $config->get('contact_title'),
        'contact_description' => $config->get('contact_description'),
    ];
    $variables['footer'] = [
        'footer_title' => $config->get('footer_title'),
        'footer_copyright' => $config->get('footer_copyright'),
    ];
    return $variables;
  }
  