<?php

use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Url;

/**
 * Implements hook_theme_suggestions_alter().
 */
function custom_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
    if($hook == 'menu'){
        $menus = ['main-lv', 'main-ru'];
        $footer_menus = ['footer-lv', 'footer-ru'];
        if(in_array($variables['menu_name'], $menus)){
            $suggestions[] = $hook . '__heder_menu';
        }
        if(in_array($variables['menu_name'], $footer_menus)){
            $suggestions[] = $hook . '__footer_menu';
        }
    }
    if($hook == 'status_messages'){
        $variables['attributes']['class'][] = 'message-box';
    }
    if($hook == 'views_view_unformatted'){
        $suggestions[] = $hook . '__gallery_grid';
    }
}

/**
 * Implements hook_preprocess_block().
 */
function custom_preprocess_block(&$variables) {
    $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $galleries = [];

    if($variables['plugin_id'] == 'views_block:first_page_header-block_1'){
        $config = \Drupal::config('system.site');
        $variables['site_name'] = $config->get('name');
        $variables['site_slogan'] = $config->get('slogan');
    }
    if($variables['plugin_id'] == 'views_block:about_block-block_1'){
        foreach ($variables['content']['#view']->result as $row) {
            $node = $row->_entity;
            if ($node->hasTranslation($language)){
                $node = $node->getTranslation($language);
            }
            $media = $node->field_attels->entity;
            if(isset($media)){
                $image = getMediaImage($media, 'wide');
            }else{
                $image = 'default';
            }
            $variables['title'] = $node->label() ?? '';
            $variables['body'] = $node->field_front_page_about_body->value ?? '';
            $variables['image'] = $image;
            $variables['url'] = $node->toUrl()->toString();
        }
    }
    if($variables['plugin_id'] == 'views_block:galleries-block_1'){
        foreach ($variables['content']['#view']->result as $row) {
            $node = $row->_entity;
            if ($node->hasTranslation($language)){
                $node = $node->getTranslation($language);
            }
            $highlight_image = $node->field_highlight->entity;
            if(isset($highlight_image)){
                $highlight = getMediaImage($highlight_image, 'fullhd');
            } else {
                $highlight = getMediaImage($node->field_bildes->entity, 'fullhd');
            }
            $galleries[] = [
                'title' => $node->label() ?? '',
                'image' => $highlight,
                'url' => $node->toUrl()->toString()
            ];
        }
        $variables['galleries_url'] = Url::fromRoute('view.galleries.page_1')->toString();
    }
    $variables['galleries'] = $galleries;

}

/**
 * Get image style url from passed media and style
 * 
 * @param object $media
 * @param string $image_style
 * @return string
 */
function getMediaImage($media, $image_style){
    $file = $media->field_media_image->entity;
    if($file->getMimeType() == 'image/gif'){
        return $file->createFileUrl(false);
    }
    $uri = $file->getFileUri();
    return ImageStyle::load($image_style)->buildUrl($uri);
}

/**
 * Implements template_peprocess_node()
 */
function custom_preprocess_node(&$variables){
    $node = $variables['node'];
    if ($node->getType() == 'par_mums') {
        $media = $node->field_open_page_image->entity;
        if(isset($media)){
            $image = getMediaImage($media, 'fullhd');
        }else{
            $image = 'default';
        }
        $variables['title'] = $node->label() ?? '';
        $variables['body'] = $node->body->value ?? '';
        $variables['image'] = $image;
        $variables['url'] = $node->toUrl()->toString();
    } else if ($node->getType() == 'galerija' && $variables['view_mode'] == 'full') {
        foreach ($node->field_bildes->getIterator() as $value) {
            $media = $value->entity;
            if(isset($media)){
                $images[] = getMediaImage($media, 'fullhd');
            }
        }
        $highlight_image = $node->field_highlight->entity;
        if(isset($highlight_image)){
            $variables['highlight_image'] = getMediaImage($highlight_image, 'fullhd');
        }
        $variables['title'] = $node->label() ?? '';
        $variables['body'] = $node->body->value ?? '';
        $variables['images'] = $images;
    } else if ($node->getType() == 'galerija' && $variables['view_mode'] == 'teaser') {
        $highlight_image = $node->field_highlight->entity;
        if(isset($highlight_image)){
            $variables['highlight_image'] = getMediaImage($highlight_image, 'fullhd');
        } else {
            $variables['highlight_image'] = getMediaImage($node->field_bildes->entity, 'fullhd');
        }
        $variables['title'] = $node->label() ?? '';
        $variables['url'] = $node->toUrl()->toString();
    }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter()
 */
function custom_theme_suggestions_page_alter(array &$suggestions, array $variables){
    if ($node = \Drupal::routeMatch()->getParameter('node')){
        $suggestions[] = 'page__node__'. $node->bundle();
    }
}

/**
 * Implements template_preprocess_field()
 */
function custom_preprocess_field(&$variables){
    if (in_array($variables['field_type'], ['text_with_summary', 'text_long', 'string_long'])){
        $variables['attributes']['class'][] = 'cke_editable';
    }
}


/**
 * Implements custom_preprocess_webform
 */
function custom_preprocess_webform(&$vars){
    $wfid = $vars["element"]["#webform_id"];
    $wf = \Drupal\webform\Entity\Webform::load($wfid);
    $vars["title"] = $wf->label();
}